"""Root-cause categories: the single source of truth for diagnoses and ground truth."""

from enum import StrEnum


class RootCauseCategory(StrEnum):
    """Every root cause OpsPilot can diagnose and every scenario can be labelled with."""

    OOM_KILLED = "OOM_KILLED"
    IMAGE_PULL_ERROR = "IMAGE_PULL_ERROR"
    CONFIG_MISSING_ENV = "CONFIG_MISSING_ENV"
    MISSING_CONFIGMAP_OR_SECRET = "MISSING_CONFIGMAP_OR_SECRET"  # noqa: S105 - a label, not a secret
    LIVENESS_PROBE_MISCONFIG = "LIVENESS_PROBE_MISCONFIG"
    READINESS_PROBE_MISCONFIG = "READINESS_PROBE_MISCONFIG"
    INSUFFICIENT_RESOURCES = "INSUFFICIENT_RESOURCES"
    SCHEDULING_CONSTRAINT = "SCHEDULING_CONSTRAINT"
    DEPENDENCY_UNAVAILABLE = "DEPENDENCY_UNAVAILABLE"
    SERVICE_MISCONFIG = "SERVICE_MISCONFIG"
    BAD_ROLLOUT = "BAD_ROLLOUT"
    BAD_COMMAND = "BAD_COMMAND"
    INIT_CONTAINER_FAILURE = "INIT_CONTAINER_FAILURE"
    PVC_PENDING = "PVC_PENDING"
    UNKNOWN = "UNKNOWN"
